version: '3.8'
services:
#aplicação
  app:
    container_name: laravel_docker_datacenter_app
    build: 
      context: ./
      dockerfile: docker/php/Dockerfile
      args:
        - APP_ENV=${APP_ENV}
    restart: always
    working_dir: /var/www   
    env_file: .env
    volumes:
      - ./:/var/www      
    environment:
      - COMPOSER_HOME=/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
      - APP_KEY=${APP_KEY}
      #- DB_HOST=127.0.0.1
      #- DB_PORT=5436
    depends_on:
      - db
    networks:
      - mynet  
    
#servidor web - nginx
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile    
    container_name: laravel_docker_datacenter_nginx
    restart: always
    volumes:
      - ./:/var/www      
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/access.log:/var/log/nginx/access.log
      - ./docker/nginx/error.log:/var/log/nginx/error.log
    networks:
      - mynet
    ports:
      - "80:80"
    depends_on:    
      - app
   
#servidor de banco de dados
  db:
    build:
      context: ./
      dockerfile: docker/db/DockerFile
    container_name: laravel_docker_datacenter_db
    env_file: .env
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data    
    volumes:      
      - $HOME/pgdata:/var/lib/postgresql/data
      ##- ./docker/db/scripts/docker-user-create-db.sh:/docker-entrypoint-initdb.d/docker-user-create-db.sh  
    networks:
      - mynet
    ports:
      - "5436:5432"
    restart: unless-stopped

volumes:
  pgdata:
    driver: local

networks:
  mynet:
    name: mynet
    ipam:
      driver: default
      config:
      - subnet: 172.20.0.0/16